### PR TITLE
CadastralWebMap as LV95

### PR DESCRIPTION
**Pull request by procrastinatio**
1. Using LV95 for CWM

2. Only one request per tile

For **one** WMTS tile, we have only **one** WMS request of 256x256 pixels

```
[2017-05-04 14:47:18,335] mapproxy.proj - DEBUG - transformed from SRS('EPSG:2056') to SRS('EPSG:4326') ((2548000.0, 1094000.0, 2612000.0, 1158000.0) -> (6.760350993364026, 45.99555099412557, 7.5951707716167745, 46.57326339331463))
[2017-05-04 14:47:18,338] mapproxy.proj - DEBUG - transformed from SRS('EPSG:2056') to SRS('EPSG:21781') ((2548000.0, 1094000.0, 2612000.0, 1158000.0) -> (548000.3202401685, 93999.66853610275, 612000.8686208094, 158000.11968589635))
[2017-05-04 14:47:18,338] mapproxy.proj - DEBUG - transformed from SRS('EPSG:21781') to SRS('EPSG:4326') ((548000.0, 94000.0, 612000.0, 158000.0) -> (6.760346768229868, 45.99555323286555, 7.595167669286507, 46.57326363665062))
[2017-05-04 14:47:18,339] mapproxy.proj - DEBUG - transformed from SRS('EPSG:21781') to SRS('EPSG:4326') ((548000.0, 94000.0, 612000.0, 158000.0) -> (6.760346768229868, 45.99555323286555, 7.595167669286507, 46.57326363665062))
[2017-05-04 14:47:18,440] mapproxy.source.request - INFO - GET http://wms.cadastralwebmap.ch/WMS?styles=&format=image%2Fpng&height=256&bbox=548000.0,94000.0,612000.0,158000.0&layers=cm_wms&crs=EPSG%3A21781&service=WMS&request=GetMap&width=256&version=1.3.0 200 0.6 99
[2017-05-04 14:47:18,443] mapproxy.image - DEBUG - file(<mapproxy.image.ReadBufWrapper object at 0x7f4588b87810>) -> image
[2017-05-04 14:47:18,461] mapproxy.image - DEBUG - image -> buf(image/png)
[info] 127.0.0.1 - - [04/May/2017 14:47:18] "GET /wmts/1.0.0/ch.kantone.cadastralwebmap-farbe_current_epsg_2056/default/epsg_2056/16/2/3.png HTTP/1.1" 200 -
```

[Demo](http://wmts20.int.bgdi.ch/demo/?wmts_layer=ch.kantone.cadastralwebmap-farbe_current_epsg_2056&format=png&srs=EPSG%3A2056)

and another [One](https://web-wmts-test.dev.bgdi.ch/?host_tpl=https%3A%2F%2Fwmts%7B20-24%7D.int.bgdi.ch&raw_tpl=0&timestamp=current&use_src=0&format=png&layer=ch.kantone.cadastralwebmap-farbe&epsg=2056&lang=fr)

N.B.
- Zoom level in demo are random (no clue where where to stop)
- Demos have only 2 layers (for ease and speed)

See https://github.com/geoadmin/service-mapproxy/issues/62

### CODE REVIEW

**Comment by gjn** [comment]
@rebert Will review. If good, please merge and deploy.

**Comment by gjn** [comment]
ping @rebert It would be great to have this for tomorrow. Please review.

**Comment by rebert** [comment]
Looks good to me. With the help of @procrastinatio. As far as I can judge it LGTM: https://web-wmts-test.dev.bgdi.ch/?host_tpl=https://wmts20.int.bgdi.ch&raw_tpl=0&timestamp=current&use_src=0&format=png&layer=ch.kantone.cadastralwebmap-farbe&epsg=21781&lang=fr

But to be a reliable tester, I don't have enough know how here... sorry

**Comment by loicgasser** [comment]
Let's go!

**Pull request merged**
