### PR TITLE
Adding gutter for layer cadastralwebmap

### PR DESCRIPTION
**Pull request by procrastinatio**
This layer has **gutter** issues.

### CODE REVIEW

**Comment by loicgasser** [comment]
I can tile observe the shift mentionned in: https://github.com/geoadmin/mf-geoadmin3/issues/3057

**Comment by procrastinatio** [comment]
@loicgasser no try adding https://wtms20.prod.bgdi.ch to geo.admin.ch 3D (wait, wait, wait...if you hoepfully do not crash the backend server) you do not have any gutter.

**Comment by loicgasser** [comment]
@procrastinatio can you provide a testlink please?

**Comment by loicgasser** [comment]
Status here? We probably need to flush S3 as well. @procrastinatio can you take care for it?

**Comment by procrastinatio** [comment]
For now here is a [test link](http://wmts20.dev.bgdi.ch/demo/?wmts_layer=ch.kantone.cadastralwebmap-farbe_current_epsg_2056&format=png&srs=EPSG%3A2056). Due to the very dynamic of this layer, the reprojected tiles are **not** stored in S3. Everytime fresh from the WMS server (ouch).

**Comment by gjn** [comment]
@procrastinatio merge and deploy?

**Pull request closed without merging**
